{
    "openapi":"3.0.2",
    "info": {
        "title": "Todolist RESTful API",
        "version": "1",
        "description": "OpenAPI for Todolist RESTful API",
        "termsOfService": "https://www.programmerzamannow.com",
        "contact": {
            "name": "Eko Kurniawan Khannedy",
            "email": "echo.khannedy@gmail.com",
            "url": "https://www.programmerzamannow.com"
        },
        "license": {
            "name": "APACHE 2.0",
            "url": "https://www.apache.org/licenses/LICENSE-2.0"
        }
    },
    "servers": [
        {
            "description": "Todolist RESTful API Server",
            "url": "https://{enviroment}.programmerzamannow.com/api/v1",
            "variables": {
                "enviroment" :{
                    "description": "Server Enviroment",
                    "default": "dev",
                    "enum": [
                        "dev",
                        "qa",
                        "prod"
                    ]
                }
            }
        }
    ],
    "externalDocs": {
        "description": "Youtube Programmer Zaman Now",
        "url": "https://www.Youtube.com/c/ProgrammerZamanNow"
    },
    "paths": {
        "/todolist" :{
            "get" :{
                "tags": ["Todolist"],
                "summary": "Get all todolist",
                "description": "Get all active todolist by default",
                "parameters": [
                    {
                        "name": "Include_done",
                        "in": "query",
                        "required": false,
                        "description": "Is include done todolist",
                        "schema" :{
                            "type": "boolean",
                            "nullable": true,
                            "default" :false
                        }
                    },
                    {
                        "name": "name",
                        "in": "query",
                        "required": false,
                        "description": "Filter todolist by name",
                        "schema":{
                            "type": "string",
                            "nullable": true,
                            "minLength": 1,
                            "maxLength": 100
                        },
                        "examples": {
                            "java" :{
                                "description": "Example name java",
                                "value": "Java"
                            },
                            "php" :{
                                "description": "Example name php",
                                "value": "PHP"
                            }
                        }
                    }
                ],
                "responses": {
                    "200" :{
                        "description": "Success get all todolist ",
                        "content": {
                            "application/json":{
                                "schema" : {
                                    "$ref" : "#/components/schemas/ArrayTodolist"
                                },
                                "examples": {
                                    "success" :{
                                        "description": "Example success get all todolist",
                                        "value" : [
                                            {
                                                "id" : "1",
                                                "name" : "Java",
                                                "priority" :3,
                                                "tags" : [
                                                    "Java", "Programming"
                                                ]

                                            },
                                            {
                                                "id" : "2",
                                                "name" : "PHP",
                                                "priority" :5,
                                                "tags" : [
                                                    "PHP", "Programming"
                                                ]

                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "post" :{
                "tags": ["Todolist"],
                "summary": "Create new todolist",
                "description": "Create new todolist to database",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json" :{
                            "schema":{
                                "$ref" : "#/components/schemas/CreateOrUpdateTodolist"
                            },
                            "examples": {
                                "java" :{
                                    "description": "Example create todolist Java",
                                    "value": {
                                        "name": "Java",
                                        "priority": 3,
                                        "tags" : [
                                            "Java",
                                            "Programming"
                                        ]
                                    }
                                },
                                "php" :{
                                    "description": "Example create todolist PHP",
                                    "value": {
                                        "name": "PHP",
                                        "priority": 5,
                                        "tags" : [
                                            "PHP",
                                            "Programming"
                                        ]
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200" :{
                        "description": "Success create todolist",
                        "content": {
                            "application/json" :{
                                "schema" : {
                                    "$ref" : "#/components/schemas/Todolist"
                                },
                                "examples": {
                                    "java" :{
                                        "description": "Success create Java todolist",
                                        "value": {
                                            "id": "1",
                                            "name": "Java",
                                            "priority": 3,
                                            "tags" : [
                                                "Java",
                                                "Programming"
                                            ]
                                        }   
                                    },

                                    "php" :{
                                        "description": "Success create PHP todolist",
                                        "value": {
                                            "id": "2",
                                            "name": "PHP",
                                            "priority": 5,
                                            "tags" : [
                                                "PHP",
                                                "Programming"
                                            ]
                                        }
                                    }
                                    
                                }
                            }
                        } 
                    }
                }
            }

        },
        "/todolist/{todolistId}" :{
            "put" :{
                "tags": ["Todolist"],
                "summary": "Update extisting todolist",
                "description": "Update extisting todolist in database",
                "parameters": [
                    {
                        "$ref" : "#/components/parameters/TodolistId"
                    }
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json" :{
                            "schema":{
                                "$ref" : "#/components/schemas/CreateOrUpdateTodolist"
                             },
                            "examples": {
                                "java" :{
                                    "description": "Example create todolist Java",
                                    "value": {
                                        "name": "Java",
                                        "priority": 3,
                                        "tags" : [
                                            "Java",
                                            "Programming"
                                        ]
                                    }
                                },
                                "php" :{
                                    "description": "Example create todolist PHP",
                                    "value": {
                                        "name": "PHP",
                                        "priority": 5,
                                        "tags" : [
                                            "PHP",
                                            "Programming"
                                        ]
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {

                    "200" :{
                        "description": "Success update todolist",
                        "content": {
                            "application/json" :{
                                "schema" : {
                                    "$ref" : "#/components/schemas/Todolist"

                                },
                                "examples": {
                                    "java" :{
                                        "description": "Success update Java todolist",
                                        "value": {
                                            "id": "1",
                                            "name": "Java",
                                            "priority": 3,
                                            "tags" : [
                                                "Java",
                                                "Programming"
                                            ]
                                        }   
                                    },

                                    "php" :{
                                        "description": "Success update PHP todolist",
                                        "value": {
                                            "id": "2",
                                            "name": "PHP",
                                            "priority": 5,
                                            "tags" : [
                                                "PHP",
                                                "Programming"
                                            ]
                                        }
                                    }
                                    
                                }
                            }
                        } 
                    }
                }
            },
            "delete" :{
                "tags": ["Todolist"],
                "summary": "Delete extisting todolist",
                "description": "Delete extisting todolist in database",
                "parameters": [
                    {
                        "$ref" : "#/components/parameters/TodolistIdDelete"
                    }
                ],
                
                "responses": {
                    "200" :{
                        "description": "Success delete todolist",
                        "content": {
                            "application/json" :{
                                "schema" :{
                                    "type": "object",
                                    "properties": {
                                        "success" :{
                                            "type": "boolean"
                                        }
                                    }
                                },
                                "examples": {
                                    "success" :{
                                        "description": "Success delete todolist",
                                        "value" : {
                                            "success" : true
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "404" :{
                        "description": "Falied delete not found todolist",
                        "content": {
                            "application/json" :{
                                "schema" :{
                                    "type": "object",
                                    "properties": {
                                        "success" :{
                                            "type": "boolean"
                                        }
                                    }
                                },
                                "examples": {
                                    "falied" :{
                                        "description": "Falied delete todolist",
                                        "value" : {
                                            "success" : false
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "parameters": {
            "TodolistId" :{
                "name": "todolistId",
                "in": "path",
                "required": true,
                "description": "Todolist Id for Updated",
                "schema":{
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 100
                },
                "examples": {
                    "java" :{
                        "description": "Sample todolist id for Java",
                        "value" : "1"
                    },
                    "php" :{
                        "description": "Sample todolist id for PHP",
                        "value" : "2"
                    }
                }
            },
            "TodolistIdDelete" :{
                "name": "todolistId",
                "in": "path",
                "required": true,
                "description": "Todolist Id for Delete",
                "schema":{
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 100
                },
                "examples": {
                    "java" :{
                        "description": "Sample todolist id for Java",
                        "value" : "1"
                    },
                    "php" :{
                        "description": "Sample todolist id for PHP",
                        "value" : "2"
                    }
                }
            }
        },
        "schemas": {
            "Todolist" :{
                "type": "object",
                "properties": {
                    "id" :{
                        "type": "string"
                    },
                    "name" :{
                        "type": "string"
                    },
                    "priority" :{
                        "type": "number",
                        "format": "int32"
                    },
                    "tags" :{
                        "type": "array",
                        "items":{
                            "type": "string"
                        }
                    }
                }
            },
            "CreateOrUpdateTodolist" :{
                "type": "object",
                "properties": {
                    "name" :{
                        "type": "string",
                        "minLength": 1,
                        "required": true
                    },
                    "priority":{
                        "type": "integer",
                        "format": "int32",
                        "required": true,
                        "default": 1

                    },
                    "tags" : {
                        "type": "array",
                        "required": false,
                        "minItems": 1,
                        "items" :{
                            "type": "string",
                            "minLength": 1
                        }
                    }
                }
            },
            "ArrayTodolist" :{
                "type": "array",
                "items" :{
                 "$ref" : "#/components/schemas/Todolist"
                }
            }
        }
    }
  }